# Generated by Django 5.0 on 2025-06-10 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('services', '0002_alter_service_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title for display', max_length=200)),
                ('content', models.TextField(help_text='Main post content')),
                ('banner_image_url', models.URLField(blank=True, help_text='Optional banner image URL for the post')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this post is currently active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this post should expire (optional)', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed')),
                ('created_by', models.ForeignKey(help_text='Moderator who created this post', on_delete=django.db.models.deletion.CASCADE, related_name='outreach_posts', to=settings.AUTH_USER_MODEL)),
                ('target_categories', models.ManyToManyField(blank=True, help_text='Service categories this post targets', related_name='outreach_posts', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Outreach Post',
                'verbose_name_plural': 'Outreach Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('approve_service', 'Approved Service'), ('reject_service', 'Rejected Service'), ('approve_comment', 'Approved Comment'), ('reject_comment', 'Rejected Comment'), ('edit_service', 'Edited Service'), ('resolve_flag', 'Resolved Flag'), ('create_outreach', 'Created Outreach Post'), ('edit_outreach', 'Edited Outreach Post'), ('delete_outreach', 'Deleted Outreach Post'), ('bulk_approve_services', 'Bulk Approved Services'), ('bulk_reject_services', 'Bulk Rejected Services'), ('bulk_approve_comments', 'Bulk Approved Comments'), ('bulk_reject_comments', 'Bulk Rejected Comments')], help_text='Type of moderation action', max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Reason for the moderation action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the moderator', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('moderator', models.ForeignKey(help_text='Moderator who performed this action', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_comment', models.ForeignKey(blank=True, help_text='Comment that was moderated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='feedback.servicecomment')),
                ('target_service', models.ForeignKey(blank=True, help_text='Service that was moderated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='services.service')),
                ('target_outreach', models.ForeignKey(blank=True, help_text='Outreach post that was moderated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='moderators.outreachpost')),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='outreachpost',
            index=models.Index(fields=['is_active', '-created_at'], name='moderators__is_acti_3819db_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachpost',
            index=models.Index(fields=['created_by', '-created_at'], name='moderators__created_a6073f_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachpost',
            index=models.Index(fields=['expires_at'], name='moderators__expires_453587_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator', '-created_at'], name='moderators__moderat_3ed27f_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type', '-created_at'], name='moderators__action__458b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_service', '-created_at'], name='moderators__target__882245_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_comment', '-created_at'], name='moderators__target__6b8e90_idx'),
        ),
    ]
