# Generated by Django 5.0 on 2025-06-10 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0001_initial'),
        ('services', '0002_alter_service_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_service_submitted', 'New Service Submitted'), ('new_comment_submitted', 'New Comment Submitted'), ('service_resubmitted', 'Service Resubmitted'), ('comment_reported', 'Comment Reported'), ('system_announcement', 'System Announcement'), ('bulk_action_completed', 'Bulk Action Completed'), ('verification_required', 'Verification Required'), ('urgent_review', 'Urgent Review Required')], help_text='Type of notification', max_length=25)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Notification priority', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL for notification action')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires', null=True)),
                ('moderator', models.ForeignKey(help_text='Community moderator receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_service', models.ForeignKey(blank=True, help_text='Related service if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notifications', to='services.service')),
            ],
            options={
                'verbose_name': 'Moderator Notification',
                'verbose_name_plural': 'Moderator Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['moderator', '-created_at'], name='moderators__moderat_8af139_idx'), models.Index(fields=['moderator', 'is_read'], name='moderators__moderat_aaed42_idx'), models.Index(fields=['priority', '-created_at'], name='moderators__priorit_c4f2f6_idx')],
            },
        ),
    ]
