# Generated by Django 5.0 on 2025-06-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.CharField(default='Malaysia', help_text='Country name', max_length=100),
        ),
    ]
