# Generated by Django 5.0 on 2025-06-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community_experience',
            field=models.TextField(blank=True, help_text='Community management or moderation experience (Community Moderators only).'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Official contact number (Service Managers only).', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='official_email',
            field=models.EmailField(blank=True, help_text='Official work email for verification (Service Managers only).', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name (Service Managers and Community Moderators).', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='relevant_community',
            field=models.CharField(blank=True, help_text='Relevant community or organization (Community Moderators only).', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='service_name',
            field=models.CharField(blank=True, help_text='Name of the service or organization (Service Managers only).', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes regarding verification decision.'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['verification_requested_at'], name='core_user_verific_66d183_idx'),
        ),
    ]
