from django.core.management.base import BaseCommand
from apps.services.models import Service, ServiceCategory
from django.contrib.auth.models import User

class Command(BaseCommand):
    help = 'Load sample services data for Selangor'

    def handle(self, *args, **options):
        # Clear existing services (optional - remove if you want to keep existing data)
        Service.objects.all().delete()
        ServiceCategory.objects.all().delete()
        
        # Create categories
        categories = {
            'healthcare': ServiceCategory.objects.create(
                name='Healthcare',
                category_type='healthcare',
                description='Medical services and health facilities'
            ),
            'food': ServiceCategory.objects.create(
                name='Food Services',
                category_type='food',
                description='Food assistance and nutrition programs'
            ),
            'shelter': ServiceCategory.objects.create(
                name='Shelter & Housing',
                category_type='shelter',
                description='Temporary housing and shelter services'
            ),
            'education': ServiceCategory.objects.create(
                name='Education',
                category_type='education',
                description='Educational resources and programs'
            ),
            'emergency': ServiceCategory.objects.create(
                name='Emergency Services',
                category_type='emergency',
                description='Emergency assistance and crisis support'
            ),
            'social': ServiceCategory.objects.create(
                name='Social Services',
                category_type='social',
                description='Community support and social programs'
            ),
        }

        # Sample services data
        services_data = [
            # Healthcare Services
            {
                'name': 'Hospital Kuala Lumpur',
                'category': categories['healthcare'],
                'description': 'Major public hospital providing comprehensive medical services including emergency care, specialist consultations, and surgical procedures. 24/7 emergency services available.',
                'short_description': 'Major public hospital with comprehensive medical services and 24/7 emergency care.',
                'address': 'Jalan Pahang, 53000 Kuala Lumpur, Wilayah Persekutuan',
                'city': 'Kuala Lumpur',
                'state_province': 'Wilayah Persekutuan',
                'country': 'Malaysia',
                'phone': '+60-3-2615-5555',
                'latitude': 3.1725,
                'longitude': 101.7068,
                'current_capacity': 85,
                'max_capacity': 100,
                'current_status': 'open',
                'is_emergency_service': True,
            },
            {
                'name': 'Klinik Kesihatan Shah Alam',
                'category': categories['healthcare'],
                'description': 'Community health clinic offering primary healthcare services, maternal and child health programs, and preventive care for residents of Shah Alam.',
                'short_description': 'Community health clinic with primary healthcare and maternal/child health programs.',
                'address': 'Seksyen 7, 40000 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-5519-6144',
                'latitude': 3.0738,
                'longitude': 101.5183,
                'current_capacity': 45,
                'max_capacity': 60,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Hospital Tengku Ampuan Rahimah',
                'category': categories['healthcare'],
                'description': 'Specialist hospital in Klang providing advanced medical care including cardiology, oncology, and pediatric services. Known for excellent patient care.',
                'short_description': 'Specialist hospital with advanced medical care and excellent patient services.',
                'address': 'Jalan Langat, 41200 Klang, Selangor',
                'city': 'Klang',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-3375-7000',
                'latitude': 3.0319,
                'longitude': 101.4481,
                'current_capacity': 120,
                'max_capacity': 150,
                'current_status': 'limited',
                'is_emergency_service': True,
            },

            # Food Services
            {
                'name': 'Pertubuhan Kebajikan Makanan Selangor',
                'category': categories['food'],
                'description': 'Food bank providing free meals and groceries to low-income families. Daily hot meals served from 12pm-2pm and food packages available for families in need.',
                'short_description': 'Food bank providing free meals and groceries to low-income families.',
                'address': 'Seksyen 14, 40000 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-5511-2233',
                'latitude': 3.0667,
                'longitude': 101.5167,
                'current_capacity': 200,
                'max_capacity': 300,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Dapur Ramadan Komuniti',
                'category': categories['food'],
                'description': 'Community kitchen serving free meals during Ramadan and year-round food assistance. Volunteers welcome. Special programs for elderly and disabled residents.',
                'short_description': 'Community kitchen with free meals and special programs for elderly and disabled.',
                'address': 'Taman Megah, 47301 Petaling Jaya, Selangor',
                'city': 'Petaling Jaya',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-7957-4466',
                'latitude': 3.1048,
                'longitude': 101.6395,
                'current_capacity': 150,
                'max_capacity': 250,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Pusat Makanan Amal Subang',
                'category': categories['food'],
                'description': 'Charitable food center distributing groceries and prepared meals to families in need. Open Tuesday-Saturday, registration required for regular assistance.',
                'short_description': 'Charitable food center distributing groceries and prepared meals.',
                'address': 'USJ 1, 47620 Subang Jaya, Selangor',
                'city': 'Subang Jaya',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-8024-5577',
                'latitude': 3.0435,
                'longitude': 101.5877,
                'current_capacity': 180,
                'max_capacity': 200,
                'current_status': 'limited',
                'is_emergency_service': False,
            },

            # Shelter & Housing
            {
                'name': 'Rumah Perlindungan Wanita Selangor',
                'category': categories['shelter'],
                'description': 'Safe house for women and children escaping domestic violence. 24/7 hotline available. Provides temporary accommodation, counseling, and legal assistance.',
                'short_description': 'Safe house for women and children with 24/7 support and counseling.',
                'address': 'Seksyen 2, 40000 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-5544-7788',
                'latitude': 3.0833,
                'longitude': 101.5333,
                'current_capacity': 25,
                'max_capacity': 35,
                'current_status': 'open',
                'is_emergency_service': True,
            },
            {
                'name': 'Pusat Transit Gelandangan KL',
                'category': categories['shelter'],
                'description': 'Temporary shelter for homeless individuals providing basic accommodation, meals, and support services to help people get back on their feet.',
                'short_description': 'Temporary shelter providing accommodation and support for homeless individuals.',
                'address': 'Chow Kit, 50300 Kuala Lumpur, Wilayah Persekutuan',
                'city': 'Kuala Lumpur',
                'state_province': 'Wilayah Persekutuan',
                'country': 'Malaysia',
                'phone': '+60-3-2693-9922',
                'latitude': 3.1667,
                'longitude': 101.6833,
                'current_capacity': 40,
                'max_capacity': 50,
                'current_status': 'open',
                'is_emergency_service': True,
            },
            {
                'name': 'Rumah Selamat Anak Jalanan',
                'category': categories['shelter'],
                'description': 'Shelter and rehabilitation center for street children providing education, skills training, and family reunification services.',
                'short_description': 'Shelter and rehabilitation center for street children with education programs.',
                'address': 'Seksyen 7, 68000 Ampang, Selangor',
                'city': 'Ampang',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-4270-1133',
                'latitude': 3.1500,
                'longitude': 101.7667,
                'current_capacity': 30,
                'max_capacity': 45,
                'current_status': 'open',
                'is_emergency_service': False,
            },

            # Emergency Services
            {
                'name': 'Balai Bomba Shah Alam',
                'category': categories['emergency'],
                'description': '24/7 fire and rescue services covering Shah Alam and surrounding areas. Emergency response for fires, accidents, and natural disasters.',
                'short_description': '24/7 fire and rescue services for emergency response.',
                'address': 'Seksyen 4, 40000 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '999',
                'latitude': 3.0833,
                'longitude': 101.5167,
                'current_capacity': 0,
                'max_capacity': 0,
                'current_status': 'open',
                'is_emergency_service': True,
                'is_24_7': True,
            },
            {
                'name': 'Ibu Pejabat Polis Kontinjen Selangor',
                'category': categories['emergency'],
                'description': 'Main police headquarters for Selangor state providing law enforcement, crime investigation, and emergency response services.',
                'short_description': 'Police headquarters providing law enforcement and emergency response.',
                'address': 'Jalan Stadium, Seksyen 13, 40100 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '999',
                'latitude': 3.0667,
                'longitude': 101.5000,
                'current_capacity': 0,
                'max_capacity': 0,
                'current_status': 'open',
                'is_emergency_service': True,
                'is_24_7': True,
            },
            {
                'name': 'Pusat Bantuan Bencana Alam',
                'category': categories['emergency'],
                'description': 'Disaster relief center coordinating emergency response during floods, earthquakes, and other natural disasters. Provides evacuation assistance and supplies.',
                'short_description': 'Disaster relief center for emergency response and evacuation assistance.',
                'address': 'Bangunan SUK, 40503 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-5544-1000',
                'latitude': 3.0667,
                'longitude': 101.5167,
                'current_capacity': 500,
                'max_capacity': 1000,
                'current_status': 'open',
                'is_emergency_service': True,
            },

            # Education Services
            {
                'name': 'Pusat Pembelajaran Komuniti Selangor',
                'category': categories['education'],
                'description': 'Adult education center offering literacy programs, skills training, and vocational courses. Free classes for disadvantaged adults seeking to improve their qualifications.',
                'short_description': 'Adult education center with literacy programs and skills training.',
                'address': 'Seksyen 9, 40000 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-5511-4455',
                'latitude': 3.0667,
                'longitude': 101.5333,
                'current_capacity': 120,
                'max_capacity': 150,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Perpustakaan Awam Petaling Jaya',
                'category': categories['education'],
                'description': 'Public library with extensive collection of books, digital resources, and study spaces. Free computer and internet access, reading programs for children.',
                'short_description': 'Public library with books, digital resources, and study spaces.',
                'address': 'Jalan Amcorp, 46050 Petaling Jaya, Selangor',
                'city': 'Petaling Jaya',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-7958-3123',
                'latitude': 3.1167,
                'longitude': 101.6500,
                'current_capacity': 200,
                'max_capacity': 300,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Program Tuisyen Percuma Selayang',
                'category': categories['education'],
                'description': 'Free tutoring program for primary and secondary students from low-income families. Evening classes available Monday-Friday with qualified volunteer teachers.',
                'short_description': 'Free tutoring program for students from low-income families.',
                'address': 'Taman Selayang Utama, 68100 Batu Caves, Selangor',
                'city': 'Batu Caves',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-6136-2244',
                'latitude': 3.2333,
                'longitude': 101.6833,
                'current_capacity': 80,
                'max_capacity': 100,
                'current_status': 'open',
                'is_emergency_service': False,
            },

            # Social Services
            {
                'name': 'Jabatan Kebajikan Masyarakat Selangor',
                'category': categories['social'],
                'description': 'State social welfare department providing financial assistance, counseling services, and support programs for families, elderly, and disabled persons.',
                'short_description': 'Social welfare department providing assistance and support programs.',
                'address': 'Wisma Darul Ehsan, 40503 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-5544-2000',
                'latitude': 3.0667,
                'longitude': 101.5000,
                'current_capacity': 0,
                'max_capacity': 0,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Pusat Jagaan Warga Emas Bangi',
                'category': categories['social'],
                'description': 'Elderly care center providing day care services, healthcare, recreational activities, and social support for senior citizens in the Bangi area.',
                'short_description': 'Elderly care center with day care and recreational activities.',
                'address': 'Seksyen 4, 43650 Bandar Baru Bangi, Selangor',
                'city': 'Bangi',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-8925-4466',
                'latitude': 2.9167,
                'longitude': 101.7833,
                'current_capacity': 60,
                'max_capacity': 80,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Rumah Perlindungan Anak Yatim',
                'category': categories['social'],
                'description': 'Orphanage providing residential care, education, and emotional support for orphaned and abandoned children. Adoption and fostering services available.',
                'short_description': 'Orphanage providing care and education for orphaned children.',
                'address': 'Taman Tun Dr Ismail, 60000 Kuala Lumpur, Wilayah Persekutuan',
                'city': 'Kuala Lumpur',
                'state_province': 'Wilayah Persekutuan',
                'country': 'Malaysia',
                'phone': '+60-3-7728-3344',
                'latitude': 3.1333,
                'longitude': 101.6333,
                'current_capacity': 45,
                'max_capacity': 60,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Kaunseling Keluarga Selangor',
                'category': categories['social'],
                'description': 'Family counseling center offering marriage counseling, family therapy, and support for domestic issues. Professional counselors available by appointment.',
                'short_description': 'Family counseling center with professional counselors.',
                'address': 'Seksyen 14, 40000 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-5519-7799',
                'latitude': 3.0667,
                'longitude': 101.5167,
                'current_capacity': 0,
                'max_capacity': 0,
                'current_status': 'open',
                'is_emergency_service': False,
            },
            {
                'name': 'Pusat Sokongan OKU Selangor',
                'category': categories['social'],
                'description': 'Support center for persons with disabilities providing skills training, job placement assistance, and advocacy services. Accessible facilities and specialized programs.',
                'short_description': 'Support center for persons with disabilities and skills training.',
                'address': 'Seksyen 7, 40000 Shah Alam, Selangor',
                'city': 'Shah Alam',
                'state_province': 'Selangor',
                'country': 'Malaysia',
                'phone': '+60-3-5511-6677',
                'latitude': 3.0738,
                'longitude': 101.5183,
                'current_capacity': 100,
                'max_capacity': 120,
                'current_status': 'open',
                'is_emergency_service': False,
            },
        ]

        # Create services
        for service_data in services_data:
            service = Service.objects.create(**service_data)
            self.stdout.write(
                self.style.SUCCESS(f'Created service: {service.name}')
            )

        self.stdout.write(
            self.style.SUCCESS(f'Successfully loaded {len(services_data)} sample services!')
        ) 